# Carga de Dados da Dimensão Localidade

# Limpa a tabela
TRUNCATE DIMENSIONAL.DIM_LOCALIDADE;

# Carrega os dados
INSERT INTO DIMENSIONAL.DIM_LOCALIDADE (NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE) 
VALUES ('1001', 'Loja A', 'Rio de Janeiro', 'Sudeste');

INSERT INTO DIMENSIONAL.DIM_LOCALIDADE (NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE) 
VALUES ('1002', 'Ponto de Venda X', 'Rio de Janeiro', 'Sudeste');

INSERT INTO DIMENSIONAL.DIM_LOCALIDADE (NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE) 
VALUES ('1003', 'Loja B', 'Fortaleza', 'Nordeste');

INSERT INTO DIMENSIONAL.DIM_LOCALIDADE (NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE) 
VALUES ('1004', 'Loja C', 'Porto Alegre', 'Sul');

INSERT INTO DIMENSIONAL.DIM_LOCALIDADE (NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE) 
VALUES ('1005', 'Loja D', 'Porto Alegre', 'Sul');

INSERT INTO DIMENSIONAL.DIM_LOCALIDADE (NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE) 
VALUES ('1006', 'Loja H', 'Natal', 'Nordeste');

INSERT INTO DIMENSIONAL.DIM_LOCALIDADE (NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE) 
VALUES ('1007', 'Ponto de Venda Y', 'Porto Alegre', 'Sul');

INSERT INTO DIMENSIONAL.DIM_LOCALIDADE (NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE) 
VALUES ('1008', 'Loja K', 'Rio de Janeiro', 'Sudeste');
