# Carga de Dados da Dimensão Cliente

# Limpa a tabela
TRUNCATE DIMENSIONAL.DIM_PRODUTO;

# Carrega os dados
INSERT INTO DIMENSIONAL.DIM_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098712', 'DFGTHN6ER4RF', 'Iphone 13', 'Smartphone', 'Apple');

INSERT INTO DIMENSIONAL.DIM_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098713', 'RFGTHN6ER4RF', 'Iphone 12', 'Smartphone', 'Apple');

INSERT INTO DIMENSIONAL.DIM_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098714', 'TFGTHN6ER4RF', 'Notebook 16 GB', 'Notebook', 'Asus');

INSERT INTO DIMENSIONAL.DIM_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098715', 'HFGTHN6ER4RF', 'Camera 80 MM', 'Camera', 'Sony');

INSERT INTO DIMENSIONAL.DIM_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098716', 'SFGTHN6ER4RF', 'Ipad Mini', 'Tablet', 'Apple');

INSERT INTO DIMENSIONAL.DIM_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098717', 'MFGTHN6ER4RF', 'Camera 90 MM', 'Camera', 'Canon');

INSERT INTO DIMENSIONAL.DIM_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098718', 'NFGTHN6ER4RF', 'Impressora Colorida', 'Impressora', 'Epson');

INSERT INTO DIMENSIONAL.DIM_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098719', 'BFGTHN6ER4RF', 'Impressora InkJet', 'Impressora', 'Epson');

INSERT INTO DIMENSIONAL.DIM_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098710', 'CFGTHN6ER4RF', 'HD Externo SSD 1 TB', 'Perifericos', 'Samsung');

INSERT INTO DIMENSIONAL.DIM_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098711', 'UFGTHN6ER4RF', 'HD Externo HDD 2 TB', 'Perifericos', 'Samsung');


