# Carga de Dados da Dimensão Cliente

# Limpa a tabela
TRUNCATE DIMENSIONAL.DIM_CLIENTE;

# Carrega os dados
INSERT INTO DIMENSIONAL.DIM_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('A10984EDCF10092', 'Bob Marley', 'Rio de Janeiro', '1', '72132900');

INSERT INTO DIMENSIONAL.DIM_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('B10984EDCF10093', 'Elvis Presley', 'Rio de Janeiro', '1', '62132900');

INSERT INTO DIMENSIONAL.DIM_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('C10984EDCF10094', 'Chuck Berry', 'Fortaleza', '0', '65132900');

INSERT INTO DIMENSIONAL.DIM_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('D10984EDCF10095', 'James Brown', 'Porto Alegre', '0', '82132900');

INSERT INTO DIMENSIONAL.DIM_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('E10984EDCF10096', 'Aretha Franklin', 'Natal', '1', '22132900');

INSERT INTO DIMENSIONAL.DIM_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('F10984EDCF10097', 'Ray Charles', 'Fortaleza', '1', '67332900');

INSERT INTO DIMENSIONAL.DIM_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('G10984EDCF10098', 'Marvin Gaye', 'Natal', '1', '12132900');

INSERT INTO DIMENSIONAL.DIM_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('H10984EDCF10099', 'Bruce Springsteen', 'Porto Alegre', '0', '42132900');

INSERT INTO DIMENSIONAL.DIM_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('I10984EDCF10100', 'Neil Young', 'Rio de Janeiro', '1', '92132900');

INSERT INTO DIMENSIONAL.DIM_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('J10984EDCF10101', 'John Lennon', 'Rio de Janeiro', '1', '72132900');

